version: '3'

services:
  dev:
    build: # use the Dockerfile in the current directory
      context: .
      dockerfile: Dockerfile
    security_opt: # options needed for gdb debugging
      - seccomp:unconfined
      - apparmor:unconfined
    container_name: dev
    ports:
      - "5566:22" # SSH
      - "7777:7777" # GDB Server
    volumes:
      - ${HOME}/Repos:/src/